### ISSUE TITLE
提示 varint.sty 文件找不到：请问如何编译 2017quanguo3.tex

### ISSUE THREAD

**Issue by inix** [shaodongtang/gaokao_exam#1]
首先感谢提供的这些优秀案例。

我的环境：
mac os；texlive 2018；使用 XeLatex编译。

提示 File 'varint.sty' not found.

请问如何解决。
谢谢

**Comment by shaodongtang** [comment]
已上传。这个宏包对于高考应该没用，应该是忘记删除这宏包了。varint李清写的改积分符号的宏包，见http://www.latexstudio.net/archives/771.html

**Comment by inix** [comment]
@shaodongtang 好的。谢谢提供。
